#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_FILE="${ROOT_DIR}/docker-compose.server.yml"
ENV_FILE="${ROOT_DIR}/.env.server"
ENV_EXAMPLE="${ROOT_DIR}/.env.server.example"

usage() {
  cat <<'EOF'
TalentScope server deploy helper

Usage:
  ./scripts/deploy.sh [options]

Options:
  --configure       Recreate .env.server interactively even if it exists
  --test            Run isolated server-side pytest after deployment
  --perf            Prepare PERF DB and run 2k benchmark/recall/runtime EXPLAIN
  --no-build        Skip production application image build (--test still refreshes test image)
  -h, --help        Show this help

Default behavior:
  - If .env.server does not exist, create it interactively.
  - Blank answers use the shown default.
  - APP_SECRET_KEY / PostgreSQL password / MinIO password are generated
    automatically when left blank.
  - Existing .env.server is reused unless --configure is specified.
EOF
}

FORCE_CONFIGURE=0
RUN_TESTS=0
RUN_PERF=0
DO_BUILD=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --configure) FORCE_CONFIGURE=1 ;;
    --test) RUN_TESTS=1 ;;
    --perf) RUN_PERF=1 ;;
    --no-build) DO_BUILD=0 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

log() { printf '\n==> %s\n' "$*"; }
die() { echo "ERROR: $*" >&2; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"
}

random_hex() {
  local bytes="${1:-32}"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$bytes"
  elif [[ -r /dev/urandom ]]; then
    od -An -N"$bytes" -tx1 /dev/urandom | tr -d ' \n'
  else
    die "Cannot generate secure random value (openssl or /dev/urandom required)"
  fi
}

prompt_default() {
  local __var="$1" label="$2" default="$3" input
  read -r -p "${label} [${default}]: " input || true
  printf -v "$__var" '%s' "${input:-$default}"
}

prompt_optional() {
  local __var="$1" label="$2" input
  read -r -p "${label} (optional, Enter = empty): " input || true
  printf -v "$__var" '%s' "$input"
}

prompt_secret_or_generate() {
  local __var="$1" label="$2" generated input
  generated="$(random_hex 24)"
  read -r -s -p "${label} (Enter = auto-generate): " input || true
  printf '\n'
  printf -v "$__var" '%s' "${input:-$generated}"
}

write_env() {
  local tmp
  tmp="$(mktemp "${ROOT_DIR}/.env.server.tmp.XXXXXX")"
  chmod 600 "$tmp"
  cat >"$tmp" <<EOF
# Generated by scripts/deploy.sh. Do not commit.
TALENTSCOPE_HOST=${TALENTSCOPE_HOST}
TRAEFIK_NETWORK=${TRAEFIK_NETWORK}
TRAEFIK_ENTRYPOINT=${TRAEFIK_ENTRYPOINT}
TRAEFIK_CERTRESOLVER=${TRAEFIK_CERTRESOLVER}

APP_ENV=production
APP_SECRET_KEY=${APP_SECRET_KEY}
SESSION_COOKIE_NAME=${SESSION_COOKIE_NAME}
SESSION_TTL_SECONDS=${SESSION_TTL_SECONDS}
CSRF_COOKIE_NAME=${CSRF_COOKIE_NAME}
REDIS_KEY_PREFIX=${REDIS_KEY_PREFIX}

POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_TEST_DB=${POSTGRES_TEST_DB}
POSTGRES_PERF_DB=${POSTGRES_PERF_DB}

MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
S3_ACCESS_KEY=${MINIO_ROOT_USER}
S3_SECRET_KEY=${MINIO_ROOT_PASSWORD}
S3_BUCKET=${S3_BUCKET}

UPLOAD_MAX_FILE_SIZE_MB=50
UPLOAD_MAX_FILES_PER_SESSION=20
UPLOAD_SESSION_TTL_HOURS=24
LIBREOFFICE_BIN=soffice
LIBREOFFICE_TIMEOUT_SECONDS=120

LLM_BASE_URL=${LLM_BASE_URL}
LLM_API_KEY=${LLM_API_KEY}
LLM_MODEL=${LLM_MODEL}
VLM_BASE_URL=${VLM_BASE_URL}
VLM_API_KEY=${VLM_API_KEY}
VLM_MODEL=${VLM_MODEL}

AI_REQUEST_TIMEOUT_SECONDS=60
IDENTIFY_MAX_PAGES=5
IDENTIFY_MAX_VLM_PAGES=3
IDENTIFY_MAX_TEXT_CHARS=20000
IDENTIFY_PDF_RENDER_DPI=120
ANALYSIS_MAX_PAGES_PER_DOCUMENT=10
ANALYSIS_MAX_VLM_PAGES=5
ANALYSIS_MAX_TOTAL_TEXT_CHARS=40000
ANALYSIS_PDF_RENDER_DPI=120
ANALYSIS_CODE_CONTEXT_MAX_CHARS=12000
ANALYSIS_MAX_QUOTE_CHARS=400
ANALYSIS_MAX_SOURCE_REFS=5

EMBEDDING_BASE_URL=${EMBEDDING_BASE_URL}
EMBEDDING_API_KEY=${EMBEDDING_API_KEY}
EMBEDDING_MODEL=${EMBEDDING_MODEL}
EMBEDDING_DIMENSIONS=1024
EMBEDDING_ENABLED=${EMBEDDING_ENABLED}
EMBEDDING_REQUEST_TIMEOUT_SECONDS=60
EMBEDDING_MAX_INPUT_CHARS=8000
EMBEDDING_MAX_RETRIES=3
EMBEDDING_RETRY_BACKOFF_SECONDS=60
EOF
  mv "$tmp" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
}

configure_env() {
  log "Initial environment setup"
  echo "Press Enter to accept defaults. Secrets marked auto-generate do not need manual values."

  prompt_default TALENTSCOPE_HOST "Public host" "talentscope.openlink.kr"
  prompt_default TRAEFIK_NETWORK "Traefik external Docker network" "traefik_proxy"
  prompt_default TRAEFIK_ENTRYPOINT "Traefik HTTPS entrypoint" "websecure"
  prompt_default TRAEFIK_CERTRESOLVER "Traefik certificate resolver" "letsencrypt"

  APP_SECRET_KEY="$(random_hex 32)"
  echo "APP_SECRET_KEY: auto-generated"
  SESSION_COOKIE_NAME="ts_session"
  SESSION_TTL_SECONDS="28800"
  CSRF_COOKIE_NAME="ts_csrf"
  REDIS_KEY_PREFIX="talentscope"

  prompt_default POSTGRES_DB "PostgreSQL product DB" "talentscope"
  prompt_default POSTGRES_USER "PostgreSQL user" "talentscope"
  prompt_secret_or_generate POSTGRES_PASSWORD "PostgreSQL password"
  prompt_default POSTGRES_TEST_DB "PostgreSQL test DB" "talentscope_test"
  prompt_default POSTGRES_PERF_DB "PostgreSQL PERF DB" "talentscope_perf"

  prompt_default MINIO_ROOT_USER "MinIO user" "talentscope"
  prompt_secret_or_generate MINIO_ROOT_PASSWORD "MinIO password"
  prompt_default S3_BUCKET "MinIO bucket" "talent-scope"

  prompt_default LLM_BASE_URL "LLM base URL" "https://alzi-llm.openlink.kr"
  prompt_optional LLM_API_KEY "LLM API key"
  prompt_default LLM_MODEL "LLM model" "Qwen3-14B"

  prompt_default VLM_BASE_URL "VLM base URL" "https://alzi-vlm.openlink.kr"
  prompt_optional VLM_API_KEY "VLM API key"
  prompt_default VLM_MODEL "VLM model" "Qwen2.5-VL-7B-Instruct"

  prompt_optional EMBEDDING_BASE_URL "Embedding base URL"
  prompt_optional EMBEDDING_API_KEY "Embedding API key"
  prompt_default EMBEDDING_MODEL "Embedding model" "bge-m3"
  prompt_default EMBEDDING_ENABLED "Enable embedding now? true/false" "false"

  case "$EMBEDDING_ENABLED" in
    true|false) ;;
    *) die "EMBEDDING_ENABLED must be true or false" ;;
  esac
  if [[ "$EMBEDDING_ENABLED" == "true" && -z "$EMBEDDING_BASE_URL" ]]; then
    die "Embedding cannot be enabled with an empty EMBEDDING_BASE_URL"
  fi

  write_env
  echo "Created ${ENV_FILE} (mode 600)."
}

compose() {
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" "$@"
}

env_value() {
  local key="$1" value
  value="$(sed -n "s/^${key}=//p" "$ENV_FILE" | tail -n 1)"
  # deploy.sh writes plain values. Also tolerate simple matching single/double quotes
  # for operators who later edit .env.server manually.
  if [[ "$value" == \"*\" && "$value" == *\" ]]; then
    value="${value:1:${#value}-2}"
  elif [[ "$value" == \'*\' && "$value" == *\' ]]; then
    value="${value:1:${#value}-2}"
  fi
  printf '%s' "$value"
}

require_cmd docker
[[ -f "$COMPOSE_FILE" ]] || die "Missing $COMPOSE_FILE"
[[ -f "$ENV_EXAMPLE" ]] || die "Missing $ENV_EXAMPLE"

docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is required"

if [[ ! -f "$ENV_FILE" || "$FORCE_CONFIGURE" -eq 1 ]]; then
  if [[ -f "$ENV_FILE" && "$FORCE_CONFIGURE" -eq 1 ]]; then
    backup="${ENV_FILE}.bak.$(date +%Y%m%d%H%M%S)"
    cp -p "$ENV_FILE" "$backup"
    echo "Existing environment backed up to $backup"
  fi
  configure_env
else
  chmod 600 "$ENV_FILE"
  log "Using existing .env.server"
  echo "Run ./scripts/deploy.sh --configure to recreate it interactively."
fi

# Do not `source` the environment file. Compose parses it itself, while this
# helper reads only the small set of values required for preflight/validation.
TALENTSCOPE_HOST="$(env_value TALENTSCOPE_HOST)"
TRAEFIK_NETWORK="$(env_value TRAEFIK_NETWORK)"
POSTGRES_PASSWORD="$(env_value POSTGRES_PASSWORD)"
POSTGRES_TEST_DB="$(env_value POSTGRES_TEST_DB)"
POSTGRES_PERF_DB="$(env_value POSTGRES_PERF_DB)"
MINIO_ROOT_PASSWORD="$(env_value MINIO_ROOT_PASSWORD)"

[[ -n "$TALENTSCOPE_HOST" ]] || die "TALENTSCOPE_HOST is empty"
[[ -n "$TRAEFIK_NETWORK" ]] || die "TRAEFIK_NETWORK is empty"
[[ -n "$POSTGRES_PASSWORD" ]] || die "POSTGRES_PASSWORD is empty"
[[ -n "$MINIO_ROOT_PASSWORD" ]] || die "MINIO_ROOT_PASSWORD is empty"
[[ "$POSTGRES_TEST_DB" == *"_test"* ]] || die "POSTGRES_TEST_DB must contain _test"
[[ "$POSTGRES_PERF_DB" == *"_perf"* ]] || die "POSTGRES_PERF_DB must contain _perf"

log "Preflight"
docker network inspect "$TRAEFIK_NETWORK" >/dev/null 2>&1 \
  || die "Traefik network '$TRAEFIK_NETWORK' does not exist"
compose config >/dev/null
printf 'Host: %s\nTraefik network: %s\n' "$TALENTSCOPE_HOST" "$TRAEFIK_NETWORK"

if [[ "$DO_BUILD" -eq 1 ]]; then
  log "Building application images"
  compose build api worker beat frontend migrate
fi

log "Starting infrastructure"
compose up -d postgres redis minio
compose run --rm minio-init

log "Applying Alembic migrations"
compose run --rm migrate

log "Starting application"
compose up -d api worker beat frontend

log "Container status"
compose ps

if [[ "$RUN_TESTS" -eq 1 ]]; then
  # The test service is disposable and must reflect the current checkout even
  # when --no-build skips production application image rebuilds.
  log "Building isolated test image"
  compose --profile tools build test
  log "Running isolated pytest"
  compose --profile tools run --rm tools-db-init
  compose --profile tools run --rm test
fi

if [[ "$RUN_PERF" -eq 1 ]]; then
  log "Preparing PERF database"
  mkdir -p "${ROOT_DIR}/artifacts/search-perf-server"
  compose --profile tools run --rm tools-db-init
  compose --profile tools run --rm perf sh -lc 'DATABASE_URL="$PERF_DATABASE_URL" alembic upgrade head'
  compose --profile tools run --rm perf python scripts/search_perf_benchmark.py --reset
  compose --profile tools run --rm perf python scripts/search_perf_benchmark.py --seed --people 2000 --seed-value 0x612d
  compose --profile tools run --rm perf python scripts/search_perf_benchmark.py --benchmark --out /artifacts/search-perf-server --iterations 5
  compose --profile tools run --rm perf python scripts/search_perf_benchmark.py --recall
  compose --profile tools run --rm perf python scripts/search_perf_runtime_explain.py --limit 500 --iterations 5 --out /artifacts/search-perf-server/runtime-ann-explain.json
fi

log "Deployment complete"
echo "URL: https://${TALENTSCOPE_HOST}/"
echo "Health: https://${TALENTSCOPE_HOST}/api/v1/health/ready"
echo "Logs: docker compose --env-file .env.server -f docker-compose.server.yml logs -f api"
